on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: false

jobs:
  helm_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

    - uses: Azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310  # v5

    - working-directory: chart
      run: |
        helm dependencies update .
        helm package . -d /tmp/

    - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302  # v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - if: inputs.publish
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin
        helm push /tmp/boing*.tgz oci://ghcr.io/${REPO@L}/charts
      env:
        REPO: ${{ github.repository_owner }}
