on:
  workflow_call:
    inputs:
      java_version:
        type: string
        # Current LTS release
        default: "25"
      java_distribution:
        type: string
        default: "temurin"
      publish:
        type: boolean
        default: false

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: 'maven'

      - run: mvn install -DskipTests -Dspotless.check.skip=true --batch-mode

      - if: inputs.publish
        run: mvn deploy --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
