on:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - uses: renovatebot/github-action@e09d604f8f803bb527bd8321ed5be06c460b8682  # v46
        with:
          configurationFile: .github/renovate.json
          # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
          token: ${{ secrets.RENOVATE_TOKEN }}
