on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7  # v4
        with:
          # metadata:read; actions:write, contents:write, and pull_requests:write
          # https://github.com/googleapis/release-please-action/issues/818#issuecomment-1889368155
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: maven
