on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    strategy:
      matrix:
        # Current LTS release + non-LTS releases since
        java_version: ["25", "26"]
    uses: ./.github/workflows/_lint.yml
    with:
      java_version: ${{ matrix.java_version }}

  test:
    strategy:
      matrix:
        # Current LTS release + non-LTS releases since
        java_version: ["25", "26"]
    uses: ./.github/workflows/_test.yml
    with:
      java_version: ${{ matrix.java_version }}

  jar_build:
    uses: ./.github/workflows/_jar.yml
    needs:
    - lint
    - test

  container_build:
    uses: ./.github/workflows/_container.yml
    needs:
    - lint
    - test

  chart_build:
    uses: ./.github/workflows/_chart.yml
    needs:
    - lint
    - test
