on:
  release:
    types:
    - created

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  test:
    uses: ./.github/workflows/_test.yml

  publish_jar:
    uses: ./.github/workflows/_jar.yml
    needs:
    - lint
    - test

  publish_container:
    uses: ./.github/workflows/_container.yml
    needs:
    - lint
    - test
